/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.iff.bji.ec.compiladores.krenaklogo;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import org.antlr.v4.runtime.BaseErrorListener;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.RecognitionException;
import org.antlr.v4.runtime.Recognizer;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.misc.ParseCancellationException;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

/**
 *
 * @author luanp
 */
public class IDE extends javax.swing.JFrame {
    
    private boolean hasSyntaxErrors = false;

    /**
     * Creates new form IDE
     */
    public IDE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        codeArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        terminalArea = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Krenak Logo IDE");

        codeArea.setColumns(20);
        codeArea.setRows(5);
        jScrollPane1.setViewportView(codeArea);

        jScrollPane2.setViewportView(terminalArea);

        jButton1.setText("RUN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        terminalArea.setText(" ");
        
        var code = (String) codeArea.getText();
        CharStream cs = CharStreams.fromString(code + "\n");
        KrenakLogoLexer lexer = new KrenakLogoLexer(cs);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        KrenakLogoParser parser = new KrenakLogoParser(tokens);

        String logoFileName = "temp.logo";

        // Adiciona um listener de erro personalizado para mostrar informações sobre os erros
        parser.removeErrorListeners(); // Remove os listeners padrão
        parser.addErrorListener(new BaseErrorListener() {
            @Override
            public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol,
                    int line, int charPositionInLine, String msg,
                    RecognitionException e) {
                String errorMsg = String.format("Erro de sintaxe na linha %d, posição %d: %s",
                        line, charPositionInLine, msg);
                printTerminal(errorMsg, 'e');
                hasSyntaxErrors = true;
            }
        });

        // Processa o código de entrada
        try {
            ParseTree tree = parser.prog(); // Aqui o parser será executado

            StringBuilder logoCode = new StringBuilder();

            tokens.getTokens().forEach(token -> {
                String translatedText = tradutor(token.getType());
                if (translatedText != null) {
                    logoCode.append(translatedText).append(" ");
                } else if (!token.getText().equals("<EOF>")) {
                    logoCode.append(token.getText()).append(" ");
                }
            });

            File logoFile = new File(logoFileName);
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(logoFile))) {
                writer.write(logoCode.toString());
            } catch (IOException ex) {
                Logger.getLogger(IDE.class.getName()).log(Level.SEVERE, null, ex);
            }

            printTerminal("O cod foi criado com sucesso!", 'i');

            // Caminho para o intérprete Logo (substitua pelo caminho correto)
            String logoInterpreter = "C:\\Program Files (x86)\\UCBLogo\\ucblogo.exe";

            // Criação do comando para executar o arquivo Logo
            ProcessBuilder pb = new ProcessBuilder(logoInterpreter, logoFileName);

            pb.redirectErrorStream(true);

            // Inicia o processo se não houver erros
            if (!hasSyntaxErrors) {
                Process process = pb.start();

                new Thread(() -> {
                    try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                        String line;
                        while ((line = reader.readLine()) != null) {
                            printTerminal(line, 'w');
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }).start();
            }

        } catch (RecognitionException | ParseCancellationException ex) {
            // Captura exceções de reconhecimento (não deveria ocorrer se o parser terminar sem erros)
            printTerminal("Erro durante a análise: " + ex.getMessage(), 'e');
        } catch (IOException ex) {
            Logger.getLogger(IDE.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDE().setVisible(true);
            }
        });
    }

    public void printTerminal(Object s) {
        // Chama o método principal com um valor padrão para classPrint
        printTerminal(s, 'n'); // Exemplo de valor padrão para classPrint
    }

    public void printTerminal(Object s, char classPrint) {

        switch (classPrint) {
            case 'w' -> {
                appendToTerminal(s, Color.YELLOW);
            }
            case 'e' -> {
                appendToTerminal(s, Color.RED);
            }
            case 'n' -> {
                appendToTerminal(s, Color.BLACK);
            }
            case 'i' -> {
                appendToTerminal(s, Color.BLUE);
            }
            default ->
                appendToTerminal(s, Color.BLACK);
        }

    }

    private void appendToTerminal(Object s, Color c) {
        String message;

        if (s instanceof String) {
            message = (String) s;
        } else {
            message = s.toString(); // Converte o objeto para String
        }
        StyledDocument doc = terminalArea.getStyledDocument();
        Style style = terminalArea.addStyle("Style", null);
        StyleConstants.setForeground(style, c);
        try {
            doc.insertString(doc.getLength(), "\n" + message, style);
        } catch (BadLocationException e) {
            e.printStackTrace();
        }
    }

    public String tradutor(int i) {
        Map<Integer, String> tokenMap = new HashMap<>();

        // Adicionando os mapeamentos
        tokenMap.put(1, "to");
        tokenMap.put(2, "end");
        tokenMap.put(3, ":");
        tokenMap.put(4, ",");
        tokenMap.put(5, "repeat");
        tokenMap.put(6, "[");
        tokenMap.put(7, "]");
        tokenMap.put(8, "if");
        tokenMap.put(9, "<");
        tokenMap.put(10, ">");
        tokenMap.put(11, "=");
        tokenMap.put(12, "make");
        tokenMap.put(13, "print");
        tokenMap.put(14, "+");
        tokenMap.put(15, "-");
        tokenMap.put(16, "*");
        tokenMap.put(17, "/");
        tokenMap.put(18, "fd");
        tokenMap.put(19, "forward");
        tokenMap.put(20, "bk");
        tokenMap.put(21, "backward");
        tokenMap.put(22, "rt");
        tokenMap.put(23, "right");
        tokenMap.put(24, "lt");
        tokenMap.put(25, "left");
        tokenMap.put(26, "cs");
        tokenMap.put(27, "clearscreen");
        tokenMap.put(28, "pu");
        tokenMap.put(29, "penup");
        tokenMap.put(30, "pd");
        tokenMap.put(31, "pendown");
        tokenMap.put(32, "ht");
        tokenMap.put(33, "hideturtle");
        tokenMap.put(34, "st");
        tokenMap.put(35, "showturtle");
        tokenMap.put(36, "home");
        tokenMap.put(37, "stop");
        tokenMap.put(38, "label");
        tokenMap.put(39, "setxy");
        tokenMap.put(40, "random");
        tokenMap.put(41, "for");

        String tokenText = tokenMap.get(i);

        return tokenText;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea codeArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane terminalArea;
    // End of variables declaration//GEN-END:variables
}
